export const ADD_LOGUSER = 'ADD_LOGUSER'
export const LOGGEDOUT = 'LOGGEDOUT'
export const ADD_PLANS = 'ADD_PLANS'
export const FAILED_PLANS = 'FAILED_PLANS'
export const ADD_USERPLANS = 'ADD_USERPLANS'
export const FAILED_USERPLANS = 'FAILED_USERPLANS'




// export const ADD_ADS = 'ADD_ADS'
// export const ADS_FAILED = 'ADS_FAILED'
// export const ADS_LOADING = 'ADS_LOADING'
// export const ADD_CAT = 'ADD_CAT'
// export const CAT_FAILED = 'CAT_FAILED'
// export const CAT_LOADING = 'CAT_LOADING'
// export const ADD_SUBCAT = 'ADD_SUBCAT'
// export const SUBCAT_FAILED = 'SUBCAT_FAILED'
// export const SUBCAT_LOADING = 'SUBCAT_LOADING'
// export const ADD_LOC = 'ADD_LOC'
// export const LOC_FAILED = 'LOC_FAILED'
// export const LOC_LOADING = 'LOC_LOADING'
// export const ADD_PROVINCE = 'ADD_PROVINCE'
// export const ADD_CITY = 'ADD_CITY'
// export const ADD_USER = 'ADD_USER'
// export const USER_FAILED = 'USER_FAILED'
// export const USER_LOADING = 'USER_LOADING'
// export const ADD_CHAT_USER = 'ADD_CHAT_USER'
// export const ADD_FAV = 'ADD_FAV'
// export const FAV_FAILED = 'FAV_FAILED'
// export const FAV_LOADING = 'FAV_LOADING'
// export const DEL_FAV = 'DEL_FAV'
// export const POST_FAV = 'POST_FAV'
// export const ADD_CHATS = 'ADD_CHATS'
// export const DELETE_CHAT = 'DELETE_CHAT'
// export const CHAT_FAILED = 'CHAT_FAILED'
// export const ADD_FEAT = 'ADD_FEAT'
// export const FEAT_FAILED = 'FEAT_FAILED'
// export const POST_USER = 'POST_USER'
// export const FAILED_POST_USER = 'FAILED_POST_USER'